//! Validation logic for state machine definitions.
//!
//! This module ensures that the state machine definition is valid
//! before we try to generate code. It checks for:
//! - Valid initial state (must be a leaf, not a superstate)
//! - Event names follow snake_case convention
//! - Event names don't claim `schema` (reserved for introspection)
//! - All events have at least one transition
//! - All transitions have source and target states
//! - All referenced states exist
//! - Superstates that are used as targets have initial states

use crate::codegen::utils::to_snake_case;
use crate::types::*;
use proc_macro2::Span;
use std::collections::HashSet;
use syn::Result;

/// Return a spanned validation error when `cond` holds.
///
/// Lets each invariant in `validate` read as a single line instead of an
/// `if … { return Err(syn::Error::new(…)) }` block.
fn err_if(cond: bool, span: Span, msg: &str) -> Result<()> {
    if cond {
        Err(syn::Error::new(span, msg))
    } else {
        Ok(())
    }
}

/// Check if a string is in snake_case format.
///
/// Valid snake_case:
/// - All lowercase letters, digits, and underscores
/// - No consecutive underscores
/// - Doesn't start or end with underscore
/// - At least one character
fn is_snake_case(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }

    // Must not start or end with underscore
    if s.starts_with('_') || s.ends_with('_') {
        return false;
    }

    let mut prev_was_underscore = false;
    for ch in s.chars() {
        // Only allow lowercase, digits, and underscores
        if !ch.is_lowercase() && !ch.is_ascii_digit() && ch != '_' {
            return false;
        }

        // No consecutive underscores
        if ch == '_' {
            if prev_was_underscore {
                return false;
            }
            prev_was_underscore = true;
        } else {
            prev_was_underscore = false;
        }
    }

    true
}

impl StateMachine {
    /// Validate the state machine definition.
    ///
    /// This performs comprehensive validation to catch errors early
    /// and provide helpful error messages. It's called before code
    /// generation begins.
    ///
    /// # Errors
    ///
    /// Returns a `syn::Error` if any validation check fails.
    /// The error includes a span pointing to the problematic element
    /// and a descriptive message.
    pub fn validate(&self) -> Result<()> {
        err_if(
            self.async_mode && !cfg!(feature = "async"),
            self.name.span(),
            "`async: true` requires enabling the `async` feature on `state-machines`",
        )?;

        // Validate initial state

        // The initial state must be a leaf state, not a superstate
        // This prevents ambiguity about which child state to start in
        err_if(
            self.hierarchy.is_superstate(&self.initial),
            self.initial.span(),
            "`initial` must reference a leaf state",
        )?;

        // The initial state must be declared in the states list
        err_if(
            !self.states.iter().any(|state| state == &self.initial),
            self.initial.span(),
            "`initial` must be a member of `states`",
        )?;

        // Duplicate states are rejected while parsing, with the offending
        // span, so they never reach validation.

        // Validate events and transitions

        let mut event_names = HashSet::new();
        for event in &self.events {
            err_if(
                !event_names.insert(event.name.to_string()),
                event.name.span(),
                "duplicate event",
            )?;
            // Validate event naming convention
            // Events must be in snake_case to generate proper method names
            let event_name = event.name.to_string();
            if !is_snake_case(&event_name) {
                let suggested = to_snake_case(&event_name);
                return Err(syn::Error::new(
                    event.name.span(),
                    format!(
                        "event names must be in snake_case (e.g., '{}' instead of '{}')",
                        suggested, event_name
                    ),
                ));
            }

            // `schema` collides with the inherent `schema()` emitted under the
            // `inspect` feature. Reject it unconditionally: that feature is
            // unified across the dependency graph (`std` implies it), so
            // allowing it only while inspect is off would make it non-additive.
            err_if(
                event_name == "schema",
                event.name.span(),
                "`schema` is reserved for the introspection method generated by the `inspect` feature; rename the event",
            )?;

            // Each event must have at least one transition
            // An event with no transitions would be useless
            err_if(
                event.transitions.is_empty(),
                event.name.span(),
                "event must declare at least one transition",
            )?;

            for transition in &event.transitions {
                err_if(
                    transition.fallback && !event.branching,
                    event.name.span(),
                    "`fallback` requires `branching: true`",
                )?;
                // Each transition must have at least one source state
                err_if(
                    transition.sources.is_empty(),
                    transition.target.span(),
                    "transition must declare at least one source state",
                )?;

                // Validate and resolve the target state

                // If the target is a superstate, resolve it to its initial child
                // This is allowed, and we'll use the superstate's initial state
                let resolved_target = if self.hierarchy.is_superstate(&transition.target) {
                    match self.hierarchy.resolve_target(&transition.target) {
                        Some(resolved) => resolved,
                        None => {
                            // Superstate has no initial state specified
                            return Err(syn::Error::new(
                                transition.target.span(),
                                "superstate target must declare an initial child",
                            ));
                        }
                    }
                } else {
                    transition.target.clone()
                };

                // The resolved target must be a declared leaf state
                err_if(
                    !self.states.iter().any(|state| state == &resolved_target),
                    transition.target.span(),
                    "target state not declared in `states`",
                )?;

                // Validate source states

                for source in &transition.sources {
                    // Check if this is a declared leaf state
                    let is_leaf = self.states.iter().any(|state| state == source);
                    // Check if this is a declared superstate
                    let is_super = self.hierarchy.is_superstate(source);

                    // Source must be either a leaf or a superstate
                    err_if(
                        !(is_leaf || is_super),
                        source.span(),
                        "source state not declared in `states` or superstates",
                    )?;

                    // If it's a superstate, verify it has descendants
                    // This catches edge cases where a superstate was declared
                    // but has no children (which should be caught earlier,
                    // but we check again for robustness)
                    err_if(
                        self.hierarchy.expand_state(source, &self.states).is_empty(),
                        source.span(),
                        "superstate does not resolve to any leaf states",
                    )?;
                }
            }
        }

        for state in &self.states {
            for edges in crate::codegen::branching::groups(self, state) {
                let event = self
                    .events
                    .iter()
                    .find(|event| event.name == edges[0].event)
                    .unwrap();
                if edges.len() > 1 {
                    err_if(
                        !event.branching,
                        event.name.span(),
                        "ambiguous transition: use `branching: true` for guarded choices",
                    )?;
                }
                if event.branching {
                    for (index, edge) in edges.iter().enumerate() {
                        let guarded =
                            !edge.selection.guards.is_empty() || !edge.selection.unless.is_empty();
                        err_if(
                            if edge.fallback {
                                guarded || index + 1 != edges.len()
                            } else {
                                !guarded
                            },
                            edge.event.span(),
                            "branch candidates require transition guards; a guardless `fallback: true` must be last",
                        )?;
                    }
                }
            }
        }

        // Validate global callback filters

        // Every state referenced in a `from`/`to` filter must be a declared
        // leaf or superstate, and every event in an `on` filter must be a
        // declared event. Otherwise a typo would silently never match.
        let buckets = [
            &self.callbacks.before,
            &self.callbacks.after,
            &self.callbacks.around,
            &self.callbacks.on_error,
        ];
        for callback in buckets.iter().copied().flatten() {
            for filter in [&callback.from, &callback.to].into_iter().flatten() {
                for state in filter {
                    let is_leaf = self.states.iter().any(|s| s == state);
                    let is_super = self.hierarchy.is_superstate(state);
                    err_if(
                        !(is_leaf || is_super),
                        state.span(),
                        "callback filter references a state not declared in `states` or superstates",
                    )?;
                }
            }
            for filter_event in callback.on.iter().flatten() {
                err_if(
                    !self.events.iter().any(|e| &e.name == filter_event),
                    filter_event.span(),
                    "callback `on` filter references an undeclared event",
                )?;
            }
        }

        let mut lifecycle_states = HashSet::new();
        for hooks in &self.lifecycle {
            err_if(
                !self.states.contains(&hooks.state) && !self.hierarchy.is_superstate(&hooks.state),
                hooks.state.span(),
                "lifecycle references an undeclared state",
            )?;
            err_if(
                !lifecycle_states.insert(hooks.state.to_string()),
                hooks.state.span(),
                "duplicate state lifecycle",
            )?;
        }

        let mut finals = HashSet::new();
        for state in &self.final_states {
            err_if(
                !self.states.contains(state),
                state.span(),
                "final state must be a declared leaf",
            )?;
            err_if(
                !finals.insert(state.to_string()),
                state.span(),
                "duplicate final state",
            )?;
            err_if(
                self.transition_graph
                    .outgoing(state)
                    .is_some_and(|edges| !edges.is_empty()),
                state.span(),
                "final states cannot have outgoing transitions",
            )?;
        }

        // All validation passed!
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use quote::quote;

    fn validate(tokens: proc_macro2::TokenStream) -> Result<()> {
        syn::parse2::<StateMachine>(tokens)?.validate()
    }

    #[test]
    fn rejects_ambiguous_graphs() {
        for events in [
            quote! { go { transition: { from: A, to: B } } go { transition: { from: B, to: A } } },
            quote! { go { transition: { from: A, to: B } transition: { from: A, to: A } } },
        ] {
            let err = validate(quote! {
                name: Test, initial: A, states: [A, B], events { #events }
            })
            .unwrap_err();
            assert!(err.to_string().contains("duplicate") || err.to_string().contains("ambiguous"));
        }
    }

    #[test]
    fn internal_transitions_omit_targets() {
        validate(quote! {
            name: Test, initial: A, states: [A, B],
            events { ping { transition: { from: [A, B], internal: true } } }
        })
        .unwrap();
        let err = validate(quote! {
            name: Test, initial: A, states: [A],
            events { ping { transition: { from: A, to: A, internal: true } } }
        })
        .unwrap_err();
        assert!(err.to_string().contains("omit `to`"));
    }

    #[test]
    fn validates_final_states() {
        for (finals, events) in [
            (quote! { [Missing] }, quote! {}),
            (quote! { [A, A] }, quote! {}),
            (
                quote! { [A] },
                quote! { go { transition: { from: A, to: B } } },
            ),
        ] {
            let err = validate(quote! {
                name: Test, initial: A, states: [A, B],
                final_states: #finals, events { #events }
            })
            .unwrap_err();
            assert!(err.to_string().contains("final"));
        }
    }

    #[test]
    fn validates_branch_fallbacks() {
        for transitions in [
            quote! { transition: { from: A, to: B } transition: { from: A, to: A, guards: [ready] } },
            quote! { transition: { from: A, to: B, fallback: true } transition: { from: A, to: A, guards: [ready] } },
            quote! { transition: { from: A, to: B, fallback: true, guards: [ready] } },
        ] {
            let err = validate(quote! {
                name: Test, initial: A, states: [A, B],
                events { go { branching: true, #transitions } }
            })
            .unwrap_err();
            assert!(err.to_string().contains("fallback"));
        }
    }

    #[test]
    fn rejects_event_named_schema() {
        let err = validate(quote! {
            name: Doc,
            initial: Draft,
            states: [Draft, Published],
            events {
                schema { transition: { from: Draft, to: Published } }
            }
        })
        .unwrap_err();

        assert!(err.to_string().contains("`schema` is reserved"), "{err}");
    }

    #[test]
    fn rejects_duplicate_states() {
        let top_level = validate(quote! {
            name: Doc,
            initial: Draft,
            states: [Draft, Draft],
        })
        .unwrap_err();
        assert!(
            top_level.to_string().contains("duplicate state"),
            "{top_level}"
        );

        let nested = validate(quote! {
            name: Doc,
            initial: Draft,
            states: [Draft, superstate Review { state Draft }],
        })
        .unwrap_err();
        assert!(nested.to_string().contains("duplicate state"), "{nested}");
    }

    #[test]
    fn accepts_event_names_containing_schema() {
        validate(quote! {
            name: Doc,
            initial: Draft,
            states: [Draft, Published],
            events {
                publish_schema { transition: { from: Draft, to: Published } }
            }
        })
        .unwrap();
    }
}
