//! Validation logic for state machine definitions.
//!
//! This module ensures that the state machine definition is valid
//! before we try to generate code. It checks for:
//! - Valid initial state (must be a leaf, not a superstate)
//! - Event names follow snake_case convention
//! - Event names don't claim `schema` (reserved for introspection)
//! - All events have at least one transition
//! - All transitions have source and target states
//! - All referenced states exist
//! - Superstates that are used as targets have initial states

use crate::codegen::utils::to_snake_case;
use crate::types::*;
use proc_macro2::Span;
use std::collections::HashSet;
use syn::Result;

/// Return a spanned validation error when `cond` holds.
///
/// Lets each invariant in `validate` read as a single line instead of an
/// `if … { return Err(syn::Error::new(…)) }` block.
fn err_if(cond: bool, span: Span, msg: &str) -> Result<()> {
    if cond {
        Err(syn::Error::new(span, msg))
    } else {
        Ok(())
    }
}

/// Check if a string is in snake_case format.
///
/// Valid snake_case:
/// - All lowercase letters, digits, and underscores
/// - No consecutive underscores
/// - Doesn't start or end with underscore
/// - At least one character
fn is_snake_case(s: &str) -> bool {
    if s.is_empty() {
        return false;
    }

    // Must not start or end with underscore
    if s.starts_with('_') || s.ends_with('_') {
        return false;
    }

    let mut prev_was_underscore = false;
    for ch in s.chars() {
        // Only allow lowercase, digits, and underscores
        if !ch.is_lowercase() && !ch.is_ascii_digit() && ch != '_' {
            return false;
        }

        // No consecutive underscores
        if ch == '_' {
            if prev_was_underscore {
                return false;
            }
            prev_was_underscore = true;
        } else {
            prev_was_underscore = false;
        }
    }

    true
}

impl StateMachine {
    /// Validate the state machine definition.
    ///
    /// This performs comprehensive validation to catch errors early
    /// and provide helpful error messages. It's called before code
    /// generation begins.
    ///
    /// # Errors
    ///
    /// Returns a `syn::Error` if any validation check fails.
    /// The error includes a span pointing to the problematic element
    /// and a descriptive message.
    pub fn validate(&self) -> Result<()> {
        err_if(
            self.snapshot && !(self.dynamic_mode || cfg!(feature = "dynamic")),
            self.name.span(),
            "`snapshot: true` requires dynamic mode",
        )?;
        err_if(
            self.async_mode && !cfg!(feature = "async"),
            self.name.span(),
            "`async: true` requires enabling the `async` feature on `state-machines`",
        )?;

        // Validate initial state

        // The initial state must be a leaf state, not a superstate
        // This prevents ambiguity about which child state to start in
        err_if(
            self.hierarchy.is_superstate(&self.initial),
            self.initial.span(),
            "`initial` must reference a leaf state",
        )?;

        // The initial state must be declared in the states list
        err_if(
            !self.states.iter().any(|state| state == &self.initial),
            self.initial.span(),
            "`initial` must be a member of `states`",
        )?;

        // Duplicate states are rejected while parsing, with the offending
        // span, so they never reach validation.

        // Validate events and transitions

        let mut event_names = HashSet::new();
        for event in &self.events {
            err_if(
                !event_names.insert(event.name.to_string()),
                event.name.span(),
                "duplicate event",
            )?;
            // Validate event naming convention
            // Events must be in snake_case to generate proper method names
            let event_name = event.name.to_string();
            if !is_snake_case(&event_name) {
                let suggested = to_snake_case(&event_name);
                return Err(syn::Error::new(
                    event.name.span(),
                    format!(
                        "event names must be in snake_case (e.g., '{}' instead of '{}')",
                        suggested, event_name
                    ),
                ));
            }

            // `schema` collides with the inherent `schema()` emitted under the
            // `inspect` feature. Reject it unconditionally: that feature is
            // unified across the dependency graph (`std` implies it), so
            // allowing it only while inspect is off would make it non-additive.
            err_if(
                event_name == "schema",
                event.name.span(),
                "`schema` is reserved for the introspection method generated by the `inspect` feature; rename the event",
            )?;
            err_if(
                [
                    "new",
                    "initialize",
                    "is_finished",
                    "completion_events",
                    "into_dynamic",
                ]
                .contains(&event_name.as_str()),
                event.name.span(),
                "event name is reserved for a generated machine method",
            )?;

            // Each event must have at least one transition
            // An event with no transitions would be useless
            err_if(
                event.transitions.is_empty(),
                event.name.span(),
                "event must declare at least one transition",
            )?;

            for transition in &event.transitions {
                if transition.kind == Some(TransitionKind::Local) {
                    for source in &transition.sources {
                        err_if(
                            !self.hierarchy.is_superstate(source)
                                || !self.hierarchy.expand_state(source, &self.states).contains(
                                    &self
                                        .hierarchy
                                        .resolve_target(&transition.target)
                                        .unwrap_or_else(|| transition.target.clone()),
                                ),
                            source.span(),
                            "local transitions must remain inside their source superstate",
                        )?;
                    }
                }
                err_if(
                    transition.data.is_some()
                        && (transition.internal
                            || !self
                                .state_storage
                                .iter()
                                .any(|spec| spec.state_name == transition.target)
                            || self.hierarchy.is_superstate(&transition.target)),
                    transition.target.span(),
                    "`data` factories require an external transition to a data-carrying leaf",
                )?;
                err_if(
                    transition.history.is_some()
                        && (transition.internal
                            || !self.hierarchy.is_superstate(&transition.target)),
                    transition.target.span(),
                    "history targets must be external transitions to a superstate",
                )?;
                err_if(
                    transition.fallback && !event.branching,
                    event.name.span(),
                    "`fallback` requires `branching: true`",
                )?;
                // Each transition must have at least one source state
                err_if(
                    transition.sources.is_empty(),
                    transition.target.span(),
                    "transition must declare at least one source state",
                )?;

                // Validate and resolve the target state

                // If the target is a superstate, resolve it to its initial child
                // This is allowed, and we'll use the superstate's initial state
                let resolved_target = if self.hierarchy.is_superstate(&transition.target) {
                    match self.hierarchy.resolve_target(&transition.target) {
                        Some(resolved) => resolved,
                        None => {
                            // Superstate has no initial state specified
                            return Err(syn::Error::new(
                                transition.target.span(),
                                "superstate target must declare an initial child",
                            ));
                        }
                    }
                } else {
                    transition.target.clone()
                };

                // The resolved target must be a declared leaf state
                err_if(
                    !self.states.iter().any(|state| state == &resolved_target),
                    transition.target.span(),
                    "target state not declared in `states`",
                )?;

                // Validate source states

                for source in &transition.sources {
                    // Check if this is a declared leaf state
                    let is_leaf = self.states.iter().any(|state| state == source);
                    // Check if this is a declared superstate
                    let is_super = self.hierarchy.is_superstate(source);

                    // Source must be either a leaf or a superstate
                    err_if(
                        !(is_leaf || is_super),
                        source.span(),
                        "source state not declared in `states` or superstates",
                    )?;

                    // If it's a superstate, verify it has descendants
                    // This catches edge cases where a superstate was declared
                    // but has no children (which should be caught earlier,
                    // but we check again for robustness)
                    err_if(
                        self.hierarchy.expand_state(source, &self.states).is_empty(),
                        source.span(),
                        "superstate does not resolve to any leaf states",
                    )?;
                }
            }
        }

        for state in &self.states {
            for edges in crate::codegen::branching::groups(self, state) {
                let event = self
                    .events
                    .iter()
                    .find(|event| event.name == edges[0].event)
                    .unwrap();
                let mut origins = HashSet::new();
                let candidates: Vec<_> = edges
                    .iter()
                    .filter(|edge| origins.insert(edge.origin))
                    .collect();
                if candidates.len() > 1
                    || (edges.len() > 1 && edges.iter().all(|edge| edge.history.is_none()))
                {
                    err_if(
                        !event.branching,
                        event.name.span(),
                        "ambiguous transition: use `branching: true` for guarded choices",
                    )?;
                }
                if event.branching {
                    for (index, edge) in candidates.iter().enumerate() {
                        let guarded =
                            !edge.selection.guards.is_empty() || !edge.selection.unless.is_empty();
                        err_if(
                            if edge.fallback {
                                guarded || index + 1 != candidates.len()
                            } else {
                                !guarded
                            },
                            edge.event.span(),
                            "branch candidates require transition guards; a guardless `fallback: true` must be last",
                        )?;
                    }
                }
            }
        }

        // Validate global callback filters

        // Every state referenced in a `from`/`to` filter must be a declared
        // leaf or superstate, and every event in an `on` filter must be a
        // declared event. Otherwise a typo would silently never match.
        let buckets = [
            &self.callbacks.before,
            &self.callbacks.after,
            &self.callbacks.around,
            &self.callbacks.on_error,
        ];
        for callback in buckets.iter().copied().flatten() {
            for filter in [&callback.from, &callback.to].into_iter().flatten() {
                for state in filter {
                    let is_leaf = self.states.iter().any(|s| s == state);
                    let is_super = self.hierarchy.is_superstate(state);
                    err_if(
                        !(is_leaf || is_super),
                        state.span(),
                        "callback filter references a state not declared in `states` or superstates",
                    )?;
                }
            }
            for filter_event in callback.on.iter().flatten() {
                err_if(
                    !self.events.iter().any(|e| &e.name == filter_event),
                    filter_event.span(),
                    "callback `on` filter references an undeclared event",
                )?;
            }
        }

        let mut lifecycle_states = HashSet::new();
        for hooks in &self.lifecycle {
            err_if(
                !self.states.contains(&hooks.state) && !self.hierarchy.is_superstate(&hooks.state),
                hooks.state.span(),
                "lifecycle references an undeclared state",
            )?;
            err_if(
                !lifecycle_states.insert(hooks.state.to_string()),
                hooks.state.span(),
                "duplicate state lifecycle",
            )?;
        }

        let mut finals = HashSet::new();
        for state in &self.final_states {
            err_if(
                !self.states.contains(state),
                state.span(),
                "final state must be a declared leaf",
            )?;
            err_if(
                !finals.insert(state.to_string()),
                state.span(),
                "duplicate final state",
            )?;
            err_if(
                self.transition_graph
                    .outgoing(state)
                    .is_some_and(|edges| !edges.is_empty()),
                state.span(),
                "final states cannot have outgoing transitions",
            )?;
        }

        // All validation passed!
        Ok(())
    }
}

#[cfg(test)]
mod tests;
