[package]
name = "dynamic_dispatch_when"
version = "0.1.8"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
state-machines = { path = "../../state-machines", features = ["dynamic", "runtime", "serde", "std"] }
pollster.workspace = true
serde.workspace = true
serde_json.workspace = true
